services:
  mongodb:
    container_name: mongodb
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=mypass
      - MONGO_INITDB_DATABASE=admin
    ports:
      - "27017:27017"
    volumes:
      - "./data:/data/db"
    networks:
      - mongo-net

  mongo-ui:
    container_name: mongo-express
    image: mongo-express
    environment:
      #- ME_CONFIG_BASICAUTH_USERNAME=""
      #- ME_CONFIG_MONGODB_URL = "mongodb://mongodb:27017"
      #- ME_CONFIG_MONGODB_ADMINUSERNAME=root
      #- ME_CONFIG_MONGODB_ADMINPASSWORD=mypass
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=mypass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=mypass
    ports:
      - "8888:8081"
    networks:
      - mongo-net
    depends_on:
      - mongodb


networks:
  mongo-net:
    driver: bridge

